# Generated by Django 2.0.6 on 2018-06-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=64, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name_plural': 'Contatos',
                'verbose_name': 'Contato',
                'ordering': ['-created'],
            },
        ),
    ]
