# Generated by Django 2.0.6 on 2018-06-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Message',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
    ]
